codestyle checks changes

diff --git a/.github/workflows/codestyle.yml b/.github/workflows/codestyle.yml
--- a/.github/workflows/codestyle.yml
+++ b/.github/workflows/codestyle.yml
@@ -9,5 +9,15 @@ jobs:
     if: github.repository == 'azerothcore/azerothcore-wotlk'
     steps:
       - uses: actions/checkout@v4
-      - name: Check core codestyle
+      - name: AzerothCore codestyle
         run: source ./apps/ci/ci-codestyle.sh
+      - name: C++ Advanced
+        run: |
+          sudo apt update -y
+          sudo apt install -y cppcheck
+          cppcheck --force --inline-suppr --suppressions-list=./.suppress.cppcheck src/ --output-file=report.txt
+
+          if [ -s report.txt ]; then  # if file is not empty
+            cat report.txt
+            exit 1 # let github action fails
+          fi
